### ISSUE TITLE
Provide Jar with Sources

### ISSUE THREAD

**Issue by limdul79** [seaside1/jrule#18]
Currently the jrule.jar only contains the compiled classes. For development it's difficult, because no api doc is available and you can't look into the code to understand what each method does.

Would it be possible to build the jar with sources included, so the IDE can provide more information?

**Comment by seaside1** [comment]
The releases are not built with both the jar-runtime as well as the source
see: https://github.com/seaside1/jrule/releases
You can just download and attach that source when coding.

The problem with including the source-files directly in the jrule.jar is that it is difficult to do from java, the only option I have seen is to generate a zip of the sources and included that in the runtime jar. But that is not very good best practices. I will close this one for now, if anyone has a solution or proposal on how to do this, then please submit a PR, otherwise I think the workaround should be enough. I will add a documentation section about this as well.
